### ISSUE TITLE
Winit bugs on macOS

### ISSUE THREAD

**Issue by parasyte** [parasyte/pixels#13]
This is a tracking issue for bugs that affect the `invaders` example on macOS

- [x] [Game does not update while resizing.](https://github.com/rust-windowing/winit/issues/1162) Fixed by https://github.com/rust-windowing/winit/pull/1173
- [x] [Title bar does not show in fullscreen.](https://github.com/rust-windowing/winit/issues/1195)
- [x] [Closing window requires extraneous events.](https://github.com/rust-windowing/winit/issues/1117)
- [ ] Excessive CPU while resizing. (No issue filed?)

**Comment by parasyte** [comment]
Excessive CPU while resizing: Seems mostly better now with winit 0.20.0-alpha4. I see 50% CPU while dragging a corner of the window, but it goes back to normal levels immediately, even while holding the mouse button but not moving the cursor.

The CPU usage changes depending on window size; maybe it's our resize handler instead of winit? We have to recreate the `wgpu` swapchain on resize.

**Comment by parasyte** [comment]
`winit` 0.22.0 still has these issues.

**Comment by parasyte** [comment]
Update: `winit` 0.26 is going to ship with a fix for https://github.com/rust-windowing/winit/issues/1195 :tada: That leaves just the excessive CPU issue, which I think is actually our bug #174

Considering this one closed.
